name: Node CI

on: [push]

jobs:
  test:
    name: textlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: yarn and lint
        run: |
          yarn
          yarn run textlint
        env:
          CI: true
